services:
    transmitter_referral.registration.form.type:
        class: Transmitter\ReferralBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: transmitter_referral_registration }
    transmitter_referral.request_listener:
        class: Transmitter\ReferralBundle\EventListener\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments: [ @router, @doctrine.orm.entity_manager, @service_container ]
    transmitter_referral.user_register_listener:
        class: Transmitter\ReferralBundle\EventListener\UserRegisterListener
        tags:
            - { name: kernel.event_subscriber }
        arguments: [ @service_container ]
